# ชื่อของ Workflow
name: Deploy DBS Project to GitHub Pages (Complete)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build and Sync files
        run: |
          # สร้างโฟลเดอร์ _site เพื่อให้แน่ใจว่ามีอยู่จริง
          mkdir -p ./_site
          # คัดลอกไฟล์ทั้งหมดไปยังโฟลเดอร์ ./_site/
          rsync -av --progress --exclude ".git*" --exclude ".github" ./ ./_site/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './_site'
          
      # --- เพิ่มขั้นตอนที่ขาดไปกลับเข้ามา ---
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

